"""empty message

Revision ID: dd8549ebb1e6
Revises: e4d7ad18f552
Create Date: 2020-05-15 12:47:32.832659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8549ebb1e6'
down_revision = 'e4d7ad18f552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_image')
    # ### end Alembic commands ###
