"""First migration

Revision ID: e4d7ad18f552
Revises: 
Create Date: 2020-03-05 22:51:57.207885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d7ad18f552'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.add_column('trainings', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'date_created')
    op.drop_column('trainings', 'date_completed')
    # ### end Alembic commands ###
